# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright OXIDOS AUTOMOTIVE 2024.

[workspace]

resolver= "2"

members = [
    "tockloader-cli",
    "tock-process-console", 
    "tbf-parser",
    "tockloader-lib",
]
